import type { FunctionComponent } from "react";
import Head from "next/head";
import PageWithBackButton from "components/Pages/PageWithBackButton";
import { useRouter } from "next/router";
import useLeague from "lib/league/useLeague";
import LeagueCard from "components/League/LeagueCard";

interface LeagueProps {}

const League: FunctionComponent<LeagueProps> = () => {
  const router = useRouter();
  const leagueId = String(router.query.league);
  const [league, loading, error] = useLeague(leagueId);
  return (
    <>
      <Head>
        <title>League</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <PageWithBackButton pageTitle={league ? league.name : ""}>
        {league && <LeagueCard id={leagueId} league={league} />}
      </PageWithBackButton>
    </>
  );
};

export default League;
