import { FunctionComponent } from "react";
import Head from "next/head";
import PageWithBackButton from "components/Pages/PageWithBackButton";
import { Typography } from "@mui/material";
import AccountInfoCard from "components/AccountInfo/AccountInfoCard";

interface AccountProps {}

const Account: FunctionComponent<AccountProps> = () => {
  return (
    <>
      <Head>
        <title>Account</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <PageWithBackButton pageTitle="Account Info">
        <AccountInfoCard />
      </PageWithBackButton>
    </>
  );
};

export default Account;
